### ISSUE TITLE
[Bug]: Internal Exception: javalangArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by PLWatt90** [DexxKnight1/TechRevolution#1]
### General Info

- [X] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [x] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.0.1

### Describe your issue

Whenever the singleplayer world is opened to LAN, players get the following error when joining. This is on a fresh world with no modifications to the world settings.

![image](https://github.com/DexxKnight1/TechRevolution/assets/84298863/ed641f0f-4c57-431c-a08d-ca7669aeae5c)

### Steps to reproduce the issue

1. Create a new world
2. Open world to lan
3. Have another player attempt to join

### Additional Information

[latest.log](https://github.com/DexxKnight1/TechRevolution/files/12432424/latest.log)
log file from client starting and connecting

**Comment by RedstoneWizard08** [comment]
[not affiliated with the pack, just trying to help] I don't think the log will help, there's nothing except this to help diagnose:

```log
# at line 3024
[14:31:33] [Netty Client IO #0/WARN]: Packet not registered: ClientboundDisconnectPacket
[14:31:33] [Netty Client IO #0/WARN]: Packet:ClientboundDisconnectPacket 
[14:31:33] [Netty Client IO #0/WARN]: Packet data:
{
  "f_132075_": {
    "f_237194_": {
      "f_237497_": "disconnect.genericReason",
      "f_237498_": [
        "Internal Exception: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0"
      ],
      "f_237500_": []
    },
    "f_237195_": [],
    "f_237196_": {},
    "f_237197_": {}
  }
}
```
