### ISSUE TITLE
[Bug]: Bucket duping caused by stacking

### ISSUE THREAD

**Issue by jeytee84** [DexxKnight1/TechRevolution#10]
### General Info

- [ ] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1.8 - 1.2.0

### Describe your issue

The bucket of water is dupable (video: https://imgur.com/a/G1yUK18)
occured in 1.1.8, updated to 1.2.0, still persists

### Steps to reproduce the issue

Holding right click while having another stack of buckets.

### Additional Information

its not crashing but here you go
https://mclo.gs/OxLxHWY
also i didnt try it in multiplayer, but somehow it was not optional

**Comment by Micaxs** [comment]
@DexxKnight1:
This issue still remains in 1.2.1 on server, someone reported:

"weird bug. bucket duplication when having a stack of empty in inventory and placing a water bucket"

Asked if issue persists in singleplayer as well, and it does.
