### ISSUE TITLE
[Bug]: data pack validation failed

### ISSUE THREAD

**Issue by RyoNam** [DexxKnight1/TechRevolution#12]
### General Info

- [ ] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

TLauncher

### Modpack version

1.19.2

### Describe your issue

A bug happened! when i started a new world, it's showed up DATAPACK validation failed
I set at default, launch the world started at normal but when i return to main screen the world get corrupt heavily
I extreme love your modpack but it seem like there was too much bug at the moment
![image_2024-08-12_085318123](https://github.com/user-attachments/assets/58968c15-78c8-4ddb-936e-fe6ed48ae873)
![image](https://github.com/user-attachments/assets/e638b80f-0c00-4238-9bbd-39881e814e90)
[latest.log](https://github.com/user-attachments/files/16576741/latest.log)
[2024-08-12-1.log.gz](https://github.com/user-attachments/files/16576742/2024-08-12-1.log.gz)

### Additional Information

[latest.log](https://github.com/user-attachments/files/16576734/latest.log)
![image](https://github.com/user-attachments/assets/16fd4888-7d95-4728-afe1-f5eabda47ad9)
![image](https://github.com/user-attachments/assets/6694e05b-4da5-4138-97f4-d6781d00293b)

**Comment by DexxKnight1** [comment]
Only I can suggest is to reinstall the pack. This data pack incompatibility issue is on the mod devs side relevated, I can't fix that, if you look into any modpack you will find these incompatibility issue / redmarked data pack. This is the result of quick porting mods to a new minecraft version.
