### ISSUE TITLE
[Bug]: Fake Player NOT working

### ISSUE THREAD

**Issue by BugsReporter9000** [DexxKnight1/TechRevolution#13]
### General Info

- [X] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

1.2.6

### Describe your issue

every single command and setting for fake player enabling is already done and everything is enabled , still nothing 

### Steps to reproduce the issue

use a modular router for crop harvesting 

### Additional Information

that's it

**Comment by DexxKnight1** [comment]
If you are the leader of your ftb team, which I assume and the router is staying in your claimed chunks, just open the inventory, press on the team button in the top left and then on the cogwheel icon for the settings and there should be a option to allow fake players in claimed chunks.
