### ISSUE TITLE
[Bug]: crafting planks with axe consumes it

### ISSUE THREAD

**Issue by joinmod** [DexxKnight1/TechRevolution#2]
### General Info

- [X] I didn't added any mods
- [X] I get this issue consistently in single-player
- [x] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATlauncher

### Modpack version

1.0.2

### Describe your issue

when you use axe to make planks, it consumes axe. its pretty annoying at start of game when you don't have any saw

at previous version 1.0.1 i didn't saw that bug

### Steps to reproduce the issue

1. get logs and any axe
2. try craft planks
3. your axe is gone

### Additional Information

https://gist.github.com/joinmod/fe2b60534e2b8cf4270eb8933988ec51

**Comment by DexxKnight1** [comment]
The Fix is posted on my [Discord](https://discord.com/channels/831803522281635850/1038833215462461580/1151845832971264024)
