### ISSUE TITLE
[Bug]: wireless univeral terminal doesnt contain three types of terminal

### ISSUE THREAD

**Issue by TianBoxv587** [DexxKnight1/TechRevolution#5]
### General Info

- [ ] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism

### Modpack version

1.13

### Describe your issue

I cant use wireless universal teminal because it contains none

### Additional Information

<img width="473" alt="Snipaste_2024-01-19_18-03-25" src="https://github.com/DexxKnight1/TechRevolution/assets/91042118/de27123c-6292-4d0f-bbb5-f1134d906d5a">

**Comment by DexxKnight1** [comment]
Fixed in the 1.1.4 update
