### ISSUE TITLE
[Bug]: No change in Mek machine upgrades in the crafting table

### ISSUE THREAD

**Issue by TianBoxv587** [DexxKnight1/TechRevolution#6]
### General Info

- [ ] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Prism

### Modpack version

1.13

### Describe your issue

No change in Mek machine upgrades in the crafting table

### Additional Information

<img width="264" alt="Snipaste_2024-01-19_18-05-06" src="https://github.com/DexxKnight1/TechRevolution/assets/91042118/5f366179-136e-40c0-86bb-0de458c00dd0">
<img width="250" alt="Snipaste_2024-01-19_18-05-37" src="https://github.com/DexxKnight1/TechRevolution/assets/91042118/c465a973-e0c8-4def-a587-f63d529fb27a">
<img width="263" alt="Snipaste_2024-01-19_18-05-14" src="https://github.com/DexxKnight1/TechRevolution/assets/91042118/efa63fa0-2288-44f7-a716-380557e9d18e">

<img width="245" alt="Snipaste_2024-01-19_18-05-41" src="https://github.com/DexxKnight1/TechRevolution/assets/91042118/4918e36e-7a34-4926-b06e-7fe71bf6a0a7">

**Comment by DexxKnight1** [comment]
Fixed in the 1.1.4 update
